### PR TITLE
Implementation of the `pathreparam` integrator

### LINKED ISSUE #26: Geometric differentiation does not yet work
In Inverse rendering example  `invert_cbox.py` and `invert_bunny.py`, if I change the differentiated parameters to `vertex_positions` ( which have asterisk (*) on the left ),  I receive the following error:

> RuntimeError: set_gradient(): no gradients are associated with this variable (a prior call to requires_gradient() is required.)

I wonder why  no gradients when they are differentiable? How should I differentiate with them?
Thanks!

### PR DESCRIPTION
**Pull request by Speierers**
This pull request proposes new integrator that implements the [paper](https://rgl.epfl.ch/publications/Loubet2019Reparameterizing) "Reparameterizing Discontinuous Integrands for Differentiable Rendering".

**TODOs**:

- [x] Support for envmap
- [x] Support for multiple emitters
- [x] Always use convolution with adaptive kernel angular support
- [x] Add existing tests to test suite
- [x] Remove `path-reparam-old` integrator (used for comparison)
- [x] Reduce calls to `gather` and `scatter` when doubling path for control variate. 
- [ ] Write documentation
- [ ] Write tutorials

Closes #26.

### CODE REVIEW

**Comment by mmgutsche** [comment]
From the todos it seems like only documentation is missing? Is it from the API any different and would basically fix #26 ?

**Comment by Speierers** [comment]
@mmgutsche We are still working on some implementation details, especially the way this new integrator deals with envmap.
On top of that, this PR won't be merge before we merge #88 . Rebasing from this will be quite some work as well.

Feel free to give it a try, you can have a look at the test script that comes with this PR for some examples.

**Comment by udemegane** [comment]
I came here from a problem with #22, and I'd like to try the test script, what directory is it in?
Thank you.

**Comment by arpit15** [comment]
https://github.com/loubetg/mitsuba2-reparam-tests repo has some examples. I get Nan sometimes when running these scripts.

**Comment by udemegane** [comment]
I'm going to try this soon. Thanks for the quick reply!

**Comment by Speierers** [comment]
Work on this will continue in a seperate PR: #157

The reason for this is to ensure compatibility with the `pathreparam` [tests suite](https://github.com/loubetg/mitsuba2-reparam-tests).

The new PR was rebased onto `master` and now uses OptiX 7.

**Pull request closed without merging**
