### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by reiner-dolp**

### CODE REVIEW

**Comment by Speierers** [comment]
Thanks @reiner-dolp , could you please squash those 3 commits into a single one. Then I will rebase and merge those to `master`.

**Comment by reiner-dolp** [comment]
There should be a [merge with squash button](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits) in the github UI that will use the PR title as the commit message.

**Comment by reiner-dolp** [comment]
Its split up into several commits since I used the edit feature on the website.

**Comment by Speierers** [comment]
Closing this as it will be fixed in the upcoming release.

**Pull request closed without merging**
